const customCatalogOption = 'Autre / personnalisé';

const garmentModels = <String>[
  'Robe droite',
  'Robe évasée',
  'Robe longue',
  'Robe de soirée',
  'Jupe droite',
  'Jupe évasée',
  'Chemise',
  'Chemisier',
  'Pantalon',
  'Short',
  'Veste',
  'Costume',
  'Ensemble deux pièces',
  'Combinaison',
  'Boubou',
  'Tunique',
  'Kaftan',
  'Tenue traditionnelle',
  'Uniforme scolaire',
  'Tenue enfant',
  customCatalogOption,
];

const fabricTypes = <String>[
  'Wax / pagne imprimé',
  'Bazin',
  'Kita / pagne tissé',
  'Dentelle',
  'Coton',
  'Lin',
  'Jean / denim',
  'Soie',
  'Satin',
  'Velours',
  'Crêpe',
  'Mousseline',
  'Organza',
  'Polyester',
  'Viscose',
  customCatalogOption,
];

const fabricColors = <String>[
  'Noir',
  'Blanc',
  'Bleu marine',
  'Bleu ciel',
  'Rouge',
  'Bordeaux',
  'Vert',
  'Vert olive',
  'Jaune',
  'Orange',
  'Rose',
  'Violet',
  'Marron',
  'Beige',
  'Gris',
  'Or',
  'Argent',
  'Multicolore',
  customCatalogOption,
];
